/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dynamsoft_barcode_NativeBarcodeReader */

#ifndef _Included_com_dynamsoft_barcode_NativeBarcodeReader
#define _Included_com_dynamsoft_barcode_NativeBarcodeReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dynamsoft_barcode_NativeBarcodeReader
 * Method:    nativeInitLicense
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynamsoft_barcode_NativeBarcodeReader_nativeInitLicense
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_dynamsoft_barcode_NativeBarcodeReader
 * Method:    nativeCreateInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_dynamsoft_barcode_NativeBarcodeReader_nativeCreateInstance
  (JNIEnv *, jobject);

/*
 * Class:     com_dynamsoft_barcode_NativeBarcodeReader
 * Method:    nativeDestroyInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_dynamsoft_barcode_NativeBarcodeReader_nativeDestroyInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynamsoft_barcode_NativeBarcodeReader
 * Method:    nativeDecodeFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dynamsoft_barcode_NativeBarcodeReader_nativeDecodeFile
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
